Updated footer
gorod-mechty/gorod-mechty pull request #15
Opened 2017-03-09 13:33 UTC by eRadu80

2017-03-09 16:56 UTC, tadatuta requested changes

2017-03-09 16:56 UTC, tadatuta commented on blocks/contacts/contacts.bemhtml.js
> +            var link = this.ctx.elemMods.type === 'phone' ? 'tel' : 'mailto';
1. лучше получать значение текущего режима через `applyNext()`
2. у блока `link` в шаблоне ожидается специальное поле `url`, стоит использовать его
3. `this.mods` и `this.elemMods` всегда гарантируются, в отличии от `this.ctx.mods` и `this.ctx.elemMods`

В итоге должно получиться что-то вроде:

```js
var url = applyNext();

return {
    block: 'link',
    url: (this.elemMods.type === 'phone' ? 'tel' : 'mailto') + ':' + url,
    content: url
}
```

2017-03-09 16:56 UTC, tadatuta commented on blocks/social/social.bemtree.js
> +            title: 'Однокласники',
ОднокласСники («с» потерялась)

2017-03-09 16:56 UTC, tadatuta commented on blocks/social/social.bemtree.js
> +            title: 'FaceBook',
вроде они пишутся как в исходном варианте

2017-03-09 16:56 UTC, tadatuta commented on blocks/social/social.bemtree.js
> +            url: 'http://www.odnoklassniki.ru/group/54637469958162'
лучше сразу использовать те ссылки на которые идет редирект (в данном случае https://ok.ru/group/54637469958162)

2017-03-09 16:56 UTC, tadatuta commented on blocks/social/social.bemtree.js
> +            url: 'http://vk.com/gorod.mechty'
https://vk.com/gorod.mechty

2017-03-09 17:37 UTC, tadatuta approved these changes

2017-03-10 08:57 UTC, vithar requested changes

2017-03-10 08:57 UTC, vithar commented on blocks/link/link.css
> +    color: rgb(73, 166, 227);
Нельзя задавать цвет для ссылок просто так, нужно задавать для псевдокласса `:link`.

Ну и лучше не задавать для всех ссылок на странице цвет, а задавать уже внетри конкретных блоков.

2017-03-10 08:57 UTC, vithar commented on blocks/contacts/contacts.bemhtml.js
> +                attrs: { href: `${link}:${this.ctx.content}` },
`attrs` лучше задавать внутри блока `link`, а тут передавать параметр `url`.

Вообще, я бы сделал блок `contacts` как &lt;nav&gt;, а внутри элемент `contact` — &lt;a&gt;

2017-03-10 08:57 UTC, vithar commented on blocks/contacts/contacts.css
> +            :block(link) {
Тут должен быть не блок `ilnk`, а элемент блока `contacts`.

2017-03-10 12:02 UTC, vithar requested changes

2017-03-10 12:02 UTC, vithar commented on blocks/contacts/contacts.bemhtml.js
> +                elem: 'link',
Блок `link` здесь бып правильным, надо вернуть его. Но к нему миксировать элемент `link` блока `contacts.`

2017-03-10 12:02 UTC, vithar commented on blocks/contacts/__link/contacts__link.bemhtml.js
> +block('contacts')(
Этот файл не нужен, см. ниже комментарий.

2017-03-10 12:02 UTC, vithar commented on blocks/contacts/__link/contacts__link.css
> +{
Кавычка на предыдущей строке должна быть.

2017-03-10 12:02 UTC, vithar commented on blocks/contacts/__link/contacts__link.css
> +.contacts__link
:block(contacts):elem(link)

2017-03-10 12:02 UTC, vithar commented on blocks/contacts/contacts.bemhtml.js
> +                attrs: { href: (this.elemMods.type === 'phone' ? 'tel' : 'mailto') + ':' + url },
Тут вернуть, как было.

2017-03-10 12:02 UTC, vithar commented on blocks/contacts/contacts.deps.js
> +        { elem: 'link' }
Добавить ещё и блок `link` в зависимости.

2017-03-10 13:56 UTC, merged